### ISSUE TITLE
Diagram of the circuit

### ISSUE THREAD

**Issue by user-hash** [diabotic/haps_640g#2]
Hi,
this is a wonderful project, and I have all the equipment I need to start testing it, but would need some help with the schematics of the circuit. I wonder If you could share the circuit schematics , because it's difficult to see them from the photos?
Photos of the PCB pads connection on the CNL would help a lot!
Do you maybe know if there is a way to resurrect a CNL meter? My 2nd CNL was somehow restarted during disassembly, and lost the local EU units and settings so I cant use it anymore.
Many thanks for your work!

**Comment by diabotic** [comment]
Dear user, I am very sorry for de delay, since I am on the last month of my university with lots of things to deliver. 

This project also almost cost my marriage.

It also only works half of the time since alerts from the pump prevent it from interacting. 

I currently dont have a definitive schematic since I made it by trial and error.  

I put a diagram in the history folder though, but I don't know for sure if its the final one. 

CNL photos posted  - I will post more data as soon as I can.

About the CNL I lost one with the soldering - desoldering process. Took me a lot of money and time to get a new CNL 2.4 since they dont sell it easy. - I bought from Germany (https://www.diashop.de/contour-next-link-2-4-mg-dl-blutzuckermessgeraet-fuer-minimed-640g-1-stueck.html)

Thanks

**Comment by user-hash** [comment]
Hey, diabotic no worries!
I really dont want to pressure you, and personal life and education is surly more important that github repo!
I understand what you are saying about the alerts, but this is a possible a thing which could not be solved?
I have a problem with CNL disconnecting from Pi USB port using 640g uploader app, is this the same in your situation?
If you wish I could send you my CNL which rebooted to USA/Brasil units, so I cant pair it anymore...although I need to check the post costs.

**Comment by diabotic** [comment]
Hi again, 
Good question. You see, there are to different states: 
    1 - The raspbery pi connects to the CNL through the USB port. (Pazaam default solution)
    2 - The raspbery pi operates the pressing of the CNL buttons through the Optocouplers. 

For state 1 to run is simple - the CNL must be connected to the RPi USB. Nothing more
For state 2 to run, you need to disconnect the CNL USB from the RPi. I only got it through turning the CNL USB +5V down

You can see in the code that we must alter between these states for fetching the blood sugar (state 1) and then operating the CNL (state 2) 

I don't thing that the alerts issue can be solved. What I did was to disable all alerts, except for the low BS alert, so I can still get the suspension. So it corrects the BS when it goes up and then I get the 640g suspension if it goes down. 
Thats why its Haps -> Half APS :-)

About the CNL disconnection, I solved it by using oldsterIL (https://github.com/oldsterIL/600SeriesDriver) that is for Python 3

I run it from scratch every 5 minutes. so the connection is only to fetch the blood sugar. Try looking at haps.py to see how I was able to run.

My first CNL also rebooted. Unfortunately after this happened it became useless and did not pair with my pump anymore. I believe its the same thing. Maybe its a protection.  If you use mmol/dl, you can get a CNL 2.4 on ebay uk (I bought one just to realise it does not work wim mg/dl pumps) 

I still don't know how to progress with this project since it will never be able to suspend. One possible idea is to use zero basal approach, with the Haps doing micro-boluses every 5 minutes. But I am is still in early stages of research about that.

**Comment by diabotic** [comment]
To be improved on next version
